# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v6

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      - run: ls -alh /home
      - run: ls -alh /home/runner 
      - run: echo $PATH
      - run: pwd
      - run: go version

      - run: |
          git clone https://github.com/dublyo/dockerizer
          cd dockerizer
          make build
          cd build
          ls -alh
          ./dockerizer help

      - run: |
          ls -alh
          echo log1
          ls -alh dockerizer
  
      - run: |
          curl -O github.com/dublyo/dockerizer-linux 
          ls -alh
          echo droit-modif
          chmod +x ./dockerizer-linux
          ls -alh
          echo exec-test
          ./dockerizer-linux -v .
          echo test-tar
          file dockerizer-linux
          
      - run: |
          cd cmd/install 
          go mod tidy
          go run main.go
          
      - run: |
          echo v2
          cd cmd/install
          go run Install-if-v2.go
          terraform version
          docker --version
      - run: ls -alh /home/runner/.local/bin
      - run: |
         mkdir exec
         cp cmd/install/Install-if-v2.go exec
         cp cmd/install/config.json exec
      - run: |
          cd cmd/install
          echo v1
          sudo go run Install.go
      - run: ls -alh /home/runner/.local/bin
      - name: test exécution
        run: sudo k3s

      - run: terraform version

      - name: log
        run: ls -alh & pwd

      - name: log2
        run: sudo cp install-k3s.sh /home

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo test, and deploy your project.
          sudo chmod +x /home/install-k3s.sh
          ls /home -alh
   ##       sudo /home/install-k3s.sh
