name: CI
permissions:
  contents: read 
  pull-requests: write
  
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6.0.2

      - run: ls -alh /home
      - run: ls -alh /home/runner 
      - run: echo $PATH
      - run: pwd
      - run: go version

      - run: |
          git clone https://github.com/dublyo/dockerizer
          cd dockerizer
          echo exec-go-build
          mkdir dockerizer-musl
          CGO_ENABLED=0 GOOS=linux go build -ldflags="-w -s" -o ./dockerizer-musl/dockerizer ./cmd/dockerizer  
          ls -alh dockerizer-musl
          echo exec-musl
          ./dockerizer-musl/dockerizer help

      - uses: actions/upload-artifact@v7.0.1
        with:
          name: my-artifact
          path: ./dockerizer/dockerizer-musl/dockerizer

      - run: |
          ls -alh
          echo log1
          ls -alh dockerizer
          
      - run: |
          cd cmd/install 
          go mod tidy
          go run main.go

      - run: CGO_ENABLED=0 GOOS=linux go build -ldflags="-w -s" -o ./install_mise install_mise.go
      - run: ./install_mise
      
      - run: ls -alh /home/runner/.local/share/mise/installs
      - run: |
          ls -alh /home/runner/.local/share/mise/installs/terraform 
          echo verif1
          ls -alh /home/runner/.local/share/mise/installs/aqua-arttor-helmify
          echo verif3 
          ls -alh /home/runner/.local/share/mise/installs/http-dockerizer
      - run: |
          echo start
          eval "$(mise activate bash)"
          terraform version
          dockerizer version
 
      - run: |
          echo v2
          cd cmd/install
          go run Test2.go
        
      - run: ls -alh /home/runner/.local/bin
      - run: |
         mkdir exec
         cp cmd/install/Test2.go exec/main.go
         cp cmd/install/config.json exec
         cp cmd/install/go.mod exec
         cd exec
         ls -alh
         dockerizer plan
         echo detect
         dockerizer detect
         dockerizer
         echo 'Voici le dockerfile'
         cat Dockerfile 
         echo 'voici docker compose'
         cat docker-compose.yml
         
      - name: test exécution
        run: k3s --version

  build-dockerizer:
    runs-on: ubuntu-latest
    steps:
      - name: build dockerizer 
        run: |
          git clone https://github.com/dublyo/dockerizer
          cd dockerizer
          echo exec-go-build
          mkdir dockerizer-musl
          CGO_ENABLED=0 GOOS=linux go build -ldflags="-w -s" -o ./dockerizer-musl/dockerizer ./cmd/dockerizer  
          ls -alh dockerizer-musl
          echo exec-musl
          ./dockerizer-musl/dockerizer help
          
      - uses: actions/upload-artifact@v7.0.1
        with:
          name: my-artifact
          path: ./dockerizer/dockerizer-musl/dockerizer
    
  build-install_mise:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.2
        with:
          ref: main
          sparse-checkout: |
            install_mise.go
            Install.json
            .mise.toml
            go.mod
   ##       sparse-checkout-cone-mode: false
          
      - run: ls
      - run: rm Install.json
      - run: CGO_ENABLED=0 GOOS=linux go build -ldflags="-w -s" -o ./install_mise install_mise.go

      - run: ./install_mise

      - run: |
         echo 'Voici le dockerfile'
         cat Dockerfile 
         echo 'voici docker compose'
         cat docker-compose.yml

      - run: docker build -t apps .
      - run: docker run apps
      - run: ls -alh /home/runner/.local/share/mise/installs
      - run: |
          ls -alh /home/runner/.local/share/mise/installs/http-dockerizer
      - run: |
          echo start
          eval "$(mise activate bash)"
          dockerizer version
    ##      terraform version

  build-test2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.2
      - name: build
        run: |
          cd cmd/install
          go build Test2.go
      - run: |
          cd cmd/install
          ./Test2
        
      - run: ls -alh /home/runner/.local/bin
      - run: |
         mkdir exec
         cp cmd/install/Test2.go exec/main.go
         cp cmd/install/config.json exec
         cp cmd/install/go.mod exec
         cd exec
         ls -alh
         dockerizer plan
         echo detect
         dockerizer detect
         dockerizer
         echo 'Voici le dockerfile'
         cat Dockerfile 
         echo 'voici docker compose'
         cat docker-compose.yml
