name: renovate
permissions:
  contents: read 
  pull-requests: write
  
on:
 ## push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Self-hosted Renovate 
        uses: renovatebot/github-action@973d3e5a68e735a444e8c03432b66eedb343c302 # v46.2.0
        with: 
          configurationFile: .github/renovate.json
          token: ${{ secrets.RENOVATE }}
