name: renovate
permissions:
  contents: read 
  pull-requests: write
  
on:
 ## push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Self-hosted Renovate 
        uses: renovatebot/github-action@b50d2ba2bd928235abdcc14d06dfafc217f1c565 # v46.1.18
        with: 
          configurationFile: .github/renovate.json
          token: ${{ secrets.RENOVATE }}
